import { fixupPluginRules } from "@eslint/compat";
import eslint from "@eslint/js";
import { defineConfig, includeIgnoreFile } from "eslint/config";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import eslintPluginAstro from "eslint-plugin-astro";
import pluginReact from "eslint-plugin-react";
import eslintPluginReactHooks from "eslint-plugin-react-hooks";
import path from "node:path";
import tseslint from "typescript-eslint";

// eslint-plugin-react still uses context APIs removed in ESLint 10; wrap it until it ships native support.
const reactPlugin = fixupPluginRules(pluginReact);

const gitignorePath = path.resolve(import.meta.dirname, ".gitignore");

const baseConfig = defineConfig({
  extends: [eslint.configs.recommended, tseslint.configs.strictTypeChecked, tseslint.configs.stylisticTypeChecked],
  languageOptions: {
    parserOptions: {
      projectService: true,
      tsconfigRootDir: import.meta.dirname,
    },
  },
  rules: {
    "no-console": "warn",
    "no-unused-vars": "off",
    "@typescript-eslint/no-unused-vars": [
      "error",
      {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_",
        ignoreRestSiblings: true,
      },
    ],
    "@typescript-eslint/restrict-template-expressions": ["error", { allowNumber: true }],
    "@typescript-eslint/no-misused-promises": ["error", { checksVoidReturn: { attributes: false } }],
  },
});

const reactConfig = defineConfig({
  files: ["**/*.{js,jsx,ts,tsx}"],
  extends: [eslintPluginReactHooks.configs.flat["recommended-latest"]],
  plugins: { react: reactPlugin },
  languageOptions: {
    ...pluginReact.configs.flat.recommended.languageOptions,
    globals: {
      window: true,
      document: true,
    },
  },
  settings: { react: { version: "detect" } },
  rules: {
    ...pluginReact.configs.flat.recommended.rules,
    "react/react-in-jsx-scope": "off",
  },
});

const astroConfig = defineConfig({
  files: ["**/*.astro"],
  languageOptions: {
    // astro-eslint-parser does not support projectService yet and warns on every file; hand it a project path instead.
    parserOptions: { projectService: false, project: "./tsconfig.json", tsconfigRootDir: import.meta.dirname },
  },
  rules: {
    "astro/no-set-html-directive": "error",
    "astro/no-unused-css-selector": "warn",
    "astro/prefer-class-list-directive": "warn",
    // The rule's return-statement check crashes on a top-level `return Astro.redirect(...)` in frontmatter
    // (it expects every `return` inside a function); frontmatter has no function to return a callback from.
    "@typescript-eslint/no-misused-promises": ["error", { checksVoidReturn: { attributes: false, returns: false } }],
  },
});

const scriptsConfig = defineConfig({
  files: ["scripts/**/*.mjs", "tests/e2e/**/*.mjs"],
  extends: [tseslint.configs.disableTypeChecked],
  languageOptions: { globals: { console: true, process: true, fetch: true, URLSearchParams: true, URL: true } },
  rules: { "no-console": "off" },
});

// Coordinate privacy (PRD NFR): a site's coordinates must never reach a log. Any module may come to carry them, so
// no source file under src may log; a deliberate log needs an inline disable that src/lib/no-console-guard.test.ts
// allowlists by file and count. The guard also fails when this scope narrows for any file.
const noConsoleConfig = defineConfig({
  files: ["src/**"],
  rules: { "no-console": "error" },
});

// Generated by `npm run db:types` and never hand-edited; its style follows the Supabase generator, and
// lint-staged's `eslint --fix` would otherwise rewrite it and trip CI's types-drift check.
// worker-configuration.d.ts is generated by `npm run cf:types` (wrangler types) from wrangler.jsonc.
const generatedIgnores = defineConfig({ ignores: ["src/lib/database.types.ts", "worker-configuration.d.ts"] });

// eslint-plugin-astro lints each client `<script>` of an .astro file as a virtual `X.astro/N.ts`. Under baseConfig's
// projectService that file is never found, the parse fails, and the plugin drops the error, so no rule ran on the
// scripts (testing-access-and-entitlement-boundary impl review F3). Lint them without type information. This block
// must stay last: prettier (eslintPluginPrettier) would otherwise re-enable on the virtual files and report bogus
// parse errors. src/lib/no-console-guard.test.ts lints a sample script end to end to prove the rules run.
const astroScriptsConfig = defineConfig({
  files: ["**/*.astro/*.ts", "**/*.astro/*.js"],
  extends: [tseslint.configs.disableTypeChecked],
  languageOptions: { parserOptions: { projectService: false, project: null } },
  rules: { "prettier/prettier": "off" },
});

export default defineConfig(
  includeIgnoreFile(gitignorePath),
  generatedIgnores,
  baseConfig,
  reactConfig,
  eslintPluginAstro.configs["flat/recommended"],
  eslintPluginAstro.configs["flat/jsx-a11y-recommended"],
  astroConfig,
  scriptsConfig,
  noConsoleConfig,
  eslintPluginPrettier,
  astroScriptsConfig,
);
