import rawCaldwell from "./caldwell.json";
import rawCaldwellMeta from "./caldwell.meta.json";
import rawCatalogue from "./messier.json";
import rawMeta from "./messier.meta.json";

/**
 * Typed, validated access to the committed deep-sky catalogue: the Messier objects and the
 * Caldwell objects a Polish observer can reach.
 *
 * `messier.json`, `caldwell.json` and their `.meta.json` files are generated by
 * `scripts/build-catalogue.mjs` from OpenNGC (CC BY-SA 4.0) and must not be edited by hand. The
 * JSON import infers loose types, so each array is validated once at module load and exported
 * through the validator's return type; a malformed regeneration fails at import, not at first use.
 */

export const DEEP_SKY_TYPES = [
  "galaxy",
  "globular-cluster",
  "open-cluster",
  "planetary-nebula",
  "nebula",
  "emission-nebula",
  "reflection-nebula",
  "supernova-remnant",
  "cluster-with-nebula",
  "asterism",
  "double-star",
  "other",
] as const;

export type DeepSkyType = (typeof DEEP_SKY_TYPES)[number];

export interface DeepSkyObject {
  /** The log key and DOM anchor, space-free: "M31" | "NGC7000" | "IC405" */
  id: string;
  /** 31, or null for a Caldwell object */
  messier: number | null;
  /** 14, or null for a Messier object */
  caldwell: number | null;
  /** "NGC 224" | "IC 4715" | "Mel 22" | "M40" | "NGC 869 / 884" */
  designation: string;
  /** What a row shows as the object's name: "M31", "NGC 7000", "NGC 869 / 884" */
  label: string;
  commonName: string | null;
  type: DeepSkyType;
  /** J2000, [0, 24) */
  raHours: number;
  /** J2000, [-90, 90] */
  decDeg: number;
  /** IAU 3-letter abbreviation; Serpens is "Ser" */
  constellation: string;
  majorAxisArcmin: number | null;
  minorAxisArcmin: number | null;
  vMag: number;
  bMag: number | null;
  /** mag/arcsec²; null where OpenNGC has no value (70 objects) */
  surfaceBrightness: number | null;
}

/** A Messier object: `messier` is set, `caldwell` never is. */
export type MessierObject = DeepSkyObject & { id: `M${number}`; messier: number; caldwell: null };

export type CaldwellObject = DeepSkyObject & { messier: null; caldwell: number };

export interface CatalogueMeta {
  source: string;
  commit: string;
  retrievedAt: string;
  licence: string;
  count: number;
}

const EXPECTED_COUNT = 110;
const EXPECTED_CALDWELL_COUNT = 61;
const CALDWELL_ID = /^(NGC|IC)[1-9][0-9]{0,3}$/;

function fail(file: string, index: number, message: string): never {
  throw new Error(`${file}[${index}]: ${message}`);
}

function isDeepSkyType(value: unknown): value is DeepSkyType {
  return typeof value === "string" && (DEEP_SKY_TYPES as readonly string[]).includes(value);
}

function requireString(file: string, o: Record<string, unknown>, key: string, index: number): string {
  const v = o[key];
  if (typeof v !== "string" || v.length === 0) {
    fail(file, index, `${key} must be a non-empty string`);
  }
  return v;
}

function requireNumber(
  file: string,
  o: Record<string, unknown>,
  key: string,
  index: number,
  min: number,
  max: number,
): number {
  const v = o[key];
  if (typeof v !== "number" || !Number.isFinite(v) || v < min || v > max) {
    fail(file, index, `${key} must be a finite number in [${min}, ${max}]`);
  }
  return v;
}

function nullableNumber(file: string, o: Record<string, unknown>, key: string, index: number): number | null {
  const v = o[key];
  if (v === null) {
    return null;
  }
  if (typeof v !== "number" || !Number.isFinite(v)) {
    fail(file, index, `${key} must be a finite number or null`);
  }
  return v;
}

function nullableString(file: string, o: Record<string, unknown>, key: string, index: number): string | null {
  const v = o[key];
  if (v === null) {
    return null;
  }
  if (typeof v !== "string" || v.length === 0) {
    fail(file, index, `${key} must be a non-empty string or null`);
  }
  return v;
}

/** The measurement fields shared by both files; identity fields are checked by each caller. */
function validateMeasurements(file: string, o: Record<string, unknown>, index: number) {
  const type = o.type;
  if (!isDeepSkyType(type)) {
    fail(file, index, `unknown type "${String(type)}"`);
  }
  const raHours = requireNumber(file, o, "raHours", index, 0, 24);
  if (raHours === 24) {
    fail(file, index, "raHours must be below 24");
  }
  return {
    designation: requireString(file, o, "designation", index),
    commonName: nullableString(file, o, "commonName", index),
    type,
    raHours,
    decDeg: requireNumber(file, o, "decDeg", index, -90, 90),
    constellation: requireString(file, o, "constellation", index),
    majorAxisArcmin: nullableNumber(file, o, "majorAxisArcmin", index),
    minorAxisArcmin: nullableNumber(file, o, "minorAxisArcmin", index),
    vMag: requireNumber(file, o, "vMag", index, -30, 30),
    bMag: nullableNumber(file, o, "bMag", index),
    surfaceBrightness: nullableNumber(file, o, "surfaceBrightness", index),
  };
}

function validateObject(entry: unknown, index: number): MessierObject {
  const file = "messier.json";
  if (typeof entry !== "object" || entry === null) {
    fail(file, index, "entry is not an object");
  }
  const o = entry as Record<string, unknown>;

  const messier = requireNumber(file, o, "messier", index, 1, EXPECTED_COUNT);
  if (!Number.isInteger(messier)) {
    fail(file, index, "messier must be an integer");
  }
  const id = requireString(file, o, "id", index);
  if (id !== `M${messier}`) {
    fail(file, index, `id "${id}" does not match messier ${messier}`);
  }

  return {
    id: id as `M${number}`,
    messier,
    caldwell: null,
    label: id,
    ...validateMeasurements(file, o, index),
  };
}

function validateCaldwellObject(entry: unknown, index: number): CaldwellObject {
  const file = "caldwell.json";
  if (typeof entry !== "object" || entry === null) {
    fail(file, index, "entry is not an object");
  }
  const o = entry as Record<string, unknown>;

  const caldwell = requireNumber(file, o, "caldwell", index, 1, 109);
  if (!Number.isInteger(caldwell)) {
    fail(file, index, "caldwell must be an integer");
  }
  if (o.messier !== null) {
    fail(file, index, "messier must be null");
  }
  const id = requireString(file, o, "id", index);
  if (!CALDWELL_ID.test(id)) {
    fail(file, index, `id "${id}" is not NGC<n> or IC<n>`);
  }
  const measurements = validateMeasurements(file, o, index);

  return { id, messier: null, caldwell, label: measurements.designation, ...measurements };
}

function validateCatalogue(input: unknown): readonly MessierObject[] {
  if (!Array.isArray(input)) {
    throw new Error("messier.json is not an array");
  }
  if (input.length !== EXPECTED_COUNT) {
    throw new Error(`messier.json has ${input.length} entries, expected ${EXPECTED_COUNT}`);
  }
  const objects = input.map((entry: unknown, index) => validateObject(entry, index));
  const seen = new Set<number>();
  for (const o of objects) {
    if (seen.has(o.messier)) {
      throw new Error(`messier.json lists M${o.messier} more than once`);
    }
    seen.add(o.messier);
  }
  return objects;
}

function validateCaldwell(input: unknown): readonly CaldwellObject[] {
  if (!Array.isArray(input)) {
    throw new Error("caldwell.json is not an array");
  }
  if (input.length !== EXPECTED_CALDWELL_COUNT) {
    throw new Error(`caldwell.json has ${input.length} entries, expected ${EXPECTED_CALDWELL_COUNT}`);
  }
  const objects = input.map((entry: unknown, index) => validateCaldwellObject(entry, index));
  const numbers = new Set<number>();
  const ids = new Set<string>();
  for (const o of objects) {
    if (numbers.has(o.caldwell)) {
      throw new Error(`caldwell.json lists C ${o.caldwell} more than once`);
    }
    if (ids.has(o.id)) {
      throw new Error(`caldwell.json lists ${o.id} more than once`);
    }
    numbers.add(o.caldwell);
    ids.add(o.id);
  }
  return objects;
}

function validateMeta(file: string, input: unknown): CatalogueMeta {
  if (typeof input !== "object" || input === null) {
    throw new Error(`${file} is not an object`);
  }
  const o = input as Record<string, unknown>;
  return {
    source: requireString(file, o, "source", -1),
    commit: requireString(file, o, "commit", -1),
    retrievedAt: requireString(file, o, "retrievedAt", -1),
    licence: requireString(file, o, "licence", -1),
    count: requireNumber(file, o, "count", -1, 0, Number.MAX_SAFE_INTEGER),
  };
}

export const MESSIER: readonly MessierObject[] = validateCatalogue(rawCatalogue);
export const CALDWELL: readonly CaldwellObject[] = validateCaldwell(rawCaldwell);
/** Messier first, then Caldwell by number. The ids are unique across both. */
export const DEEP_SKY: readonly DeepSkyObject[] = (() => {
  const all: readonly DeepSkyObject[] = [...MESSIER, ...CALDWELL];
  if (new Set(all.map((o) => o.id)).size !== all.length) {
    throw new Error("Messier and Caldwell ids overlap");
  }
  return all;
})();
export const CATALOGUE_META: CatalogueMeta = validateMeta("messier.meta.json", rawMeta);
export const CALDWELL_META: CatalogueMeta = validateMeta("caldwell.meta.json", rawCaldwellMeta);

const byNumber = new Map<number, MessierObject>(MESSIER.map((o) => [o.messier, o]));
const byId = new Map<string, DeepSkyObject>(DEEP_SKY.map((o) => [o.id, o]));

export function findMessier(n: number): MessierObject | undefined {
  return byNumber.get(n);
}

/** Any catalogue object by its id: "M31", "NGC7000", "IC405". */
export function findDeepSky(id: string): DeepSkyObject | undefined {
  return byId.get(id);
}
