import rawCatalogue from "./messier.json";
import rawMeta from "./messier.meta.json";

/**
 * Typed, validated access to the committed Messier catalogue.
 *
 * `messier.json` and `messier.meta.json` are generated by `scripts/build-catalogue.mjs`
 * from OpenNGC (CC BY-SA 4.0) and must not be edited by hand. The JSON import infers loose
 * types, so the array is validated once at module load and exported through the validator's
 * return type; a malformed regeneration fails at import, not at first use.
 */

export const MESSIER_TYPES = [
  "galaxy",
  "globular-cluster",
  "open-cluster",
  "planetary-nebula",
  "nebula",
  "emission-nebula",
  "reflection-nebula",
  "supernova-remnant",
  "cluster-with-nebula",
  "asterism",
  "double-star",
  "other",
] as const;

export type MessierType = (typeof MESSIER_TYPES)[number];

export interface MessierObject {
  /** "M31" */
  id: `M${number}`;
  /** 31 */
  messier: number;
  /** "NGC 224" | "IC 4715" | "Mel 22" | "M40" */
  designation: string;
  commonName: string | null;
  type: MessierType;
  /** J2000, [0, 24) */
  raHours: number;
  /** J2000, [-90, 90] */
  decDeg: number;
  /** IAU 3-letter abbreviation; Serpens is "Ser" */
  constellation: string;
  majorAxisArcmin: number | null;
  minorAxisArcmin: number | null;
  vMag: number;
  bMag: number | null;
  /** mag/arcsec²; null where OpenNGC has no value (70 objects) */
  surfaceBrightness: number | null;
}

export interface CatalogueMeta {
  source: string;
  commit: string;
  retrievedAt: string;
  licence: string;
  count: number;
}

const EXPECTED_COUNT = 110;

function fail(index: number, message: string): never {
  throw new Error(`messier.json[${index}]: ${message}`);
}

function isMessierType(value: unknown): value is MessierType {
  return typeof value === "string" && (MESSIER_TYPES as readonly string[]).includes(value);
}

function requireString(o: Record<string, unknown>, key: string, index: number): string {
  const v = o[key];
  if (typeof v !== "string" || v.length === 0) {
    fail(index, `${key} must be a non-empty string`);
  }
  return v;
}

function requireNumber(o: Record<string, unknown>, key: string, index: number, min: number, max: number): number {
  const v = o[key];
  if (typeof v !== "number" || !Number.isFinite(v) || v < min || v > max) {
    fail(index, `${key} must be a finite number in [${min}, ${max}]`);
  }
  return v;
}

function nullableNumber(o: Record<string, unknown>, key: string, index: number): number | null {
  const v = o[key];
  if (v === null) {
    return null;
  }
  if (typeof v !== "number" || !Number.isFinite(v)) {
    fail(index, `${key} must be a finite number or null`);
  }
  return v;
}

function nullableString(o: Record<string, unknown>, key: string, index: number): string | null {
  const v = o[key];
  if (v === null) {
    return null;
  }
  if (typeof v !== "string" || v.length === 0) {
    fail(index, `${key} must be a non-empty string or null`);
  }
  return v;
}

function validateObject(entry: unknown, index: number): MessierObject {
  if (typeof entry !== "object" || entry === null) {
    fail(index, "entry is not an object");
  }
  const o = entry as Record<string, unknown>;

  const messier = requireNumber(o, "messier", index, 1, EXPECTED_COUNT);
  if (!Number.isInteger(messier)) {
    fail(index, "messier must be an integer");
  }
  const id = requireString(o, "id", index);
  if (id !== `M${messier}`) {
    fail(index, `id "${id}" does not match messier ${messier}`);
  }
  const type = o.type;
  if (!isMessierType(type)) {
    fail(index, `unknown type "${String(type)}"`);
  }
  const raHours = requireNumber(o, "raHours", index, 0, 24);
  if (raHours === 24) {
    fail(index, "raHours must be below 24");
  }

  return {
    id: id as `M${number}`,
    messier,
    designation: requireString(o, "designation", index),
    commonName: nullableString(o, "commonName", index),
    type,
    raHours,
    decDeg: requireNumber(o, "decDeg", index, -90, 90),
    constellation: requireString(o, "constellation", index),
    majorAxisArcmin: nullableNumber(o, "majorAxisArcmin", index),
    minorAxisArcmin: nullableNumber(o, "minorAxisArcmin", index),
    vMag: requireNumber(o, "vMag", index, -30, 30),
    bMag: nullableNumber(o, "bMag", index),
    surfaceBrightness: nullableNumber(o, "surfaceBrightness", index),
  };
}

function validateCatalogue(input: unknown): readonly MessierObject[] {
  if (!Array.isArray(input)) {
    throw new Error("messier.json is not an array");
  }
  if (input.length !== EXPECTED_COUNT) {
    throw new Error(`messier.json has ${input.length} entries, expected ${EXPECTED_COUNT}`);
  }
  const objects = input.map((entry: unknown, index) => validateObject(entry, index));
  const seen = new Set<number>();
  for (const o of objects) {
    if (seen.has(o.messier)) {
      throw new Error(`messier.json lists M${o.messier} more than once`);
    }
    seen.add(o.messier);
  }
  return objects;
}

function validateMeta(input: unknown): CatalogueMeta {
  if (typeof input !== "object" || input === null) {
    throw new Error("messier.meta.json is not an object");
  }
  const o = input as Record<string, unknown>;
  return {
    source: requireString(o, "source", -1),
    commit: requireString(o, "commit", -1),
    retrievedAt: requireString(o, "retrievedAt", -1),
    licence: requireString(o, "licence", -1),
    count: requireNumber(o, "count", -1, 0, Number.MAX_SAFE_INTEGER),
  };
}

export const MESSIER: readonly MessierObject[] = validateCatalogue(rawCatalogue);
export const CATALOGUE_META: CatalogueMeta = validateMeta(rawMeta);

const byNumber = new Map<number, MessierObject>(MESSIER.map((o) => [o.messier, o]));

export function findMessier(n: number): MessierObject | undefined {
  return byNumber.get(n);
}
