import rawStars from "./bright-stars.json";

/**
 * Typed, validated access to the committed bright-star catalogue (every star to magnitude 4.5).
 *
 * `bright-stars.json` is generated by `scripts/build-stars.mjs` from the HYG database v4.1
 * (CC BY-SA 4.0) and must not be edited by hand. The array is validated once at module load, so a
 * malformed regeneration fails at import, not at first use.
 *
 * Island-safe: imports only `bright-stars.json`. Never import `./index` here, which would pull
 * `messier.json` into the browser chunk.
 */

export interface BrightStar {
  /** HYG's own id (some of these stars have no Hipparcos number) */
  id: number;
  /** Apparent visual magnitude */
  mag: number;
  /** J2000 equatorial unit vector: x towards the March equinox, z towards the north celestial pole */
  vector: readonly [number, number, number];
  /** English proper name; only the 40 brightest named stars and Polaris carry one */
  name?: string;
}

/** 925 at the pinned HYG commit; the range matches the generator's margin. */
export const BRIGHT_STAR_COUNT_RANGE = { min: 915, max: 935 } as const;
export const BRIGHT_STAR_MAX_MAG = 4.5;

function fail(index: number, message: string): never {
  throw new Error(`bright-stars.json[${index}]: ${message}`);
}

function requireNumber(o: Record<string, unknown>, key: string, index: number, min: number, max: number): number {
  const v = o[key];
  if (typeof v !== "number" || !Number.isFinite(v) || v < min || v > max) {
    fail(index, `${key} must be a finite number in [${min}, ${max}]`);
  }
  return v;
}

function validateStar(entry: unknown, index: number): BrightStar {
  if (typeof entry !== "object" || entry === null) {
    fail(index, "entry is not an object");
  }
  const o = entry as Record<string, unknown>;
  const id = requireNumber(o, "id", index, 1, Number.MAX_SAFE_INTEGER);
  if (!Number.isInteger(id)) {
    fail(index, "id must be an integer");
  }
  const star: BrightStar = {
    id,
    mag: requireNumber(o, "mag", index, -2, BRIGHT_STAR_MAX_MAG),
    vector: [
      requireNumber(o, "x", index, -1, 1),
      requireNumber(o, "y", index, -1, 1),
      requireNumber(o, "z", index, -1, 1),
    ],
  };
  if (o.name !== undefined) {
    if (typeof o.name !== "string" || o.name.length === 0) {
      fail(index, "name must be a non-empty string when present");
    }
    star.name = o.name;
  }
  return star;
}

function validateStars(input: unknown): readonly BrightStar[] {
  if (!Array.isArray(input)) {
    throw new Error("bright-stars.json is not an array");
  }
  const { min, max } = BRIGHT_STAR_COUNT_RANGE;
  if (input.length < min || input.length > max) {
    throw new Error(`bright-stars.json has ${input.length} entries, expected ${min}..${max}`);
  }
  const stars = input.map((entry: unknown, index) => validateStar(entry, index));
  const seen = new Set<number>();
  for (const s of stars) {
    if (seen.has(s.id)) {
      throw new Error(`bright-stars.json lists HYG id ${s.id} more than once`);
    }
    seen.add(s.id);
  }
  return stars;
}

export const BRIGHT_STARS: readonly BrightStar[] = validateStars(rawStars);
